safari shipping gets simpler
svn path=/trunk/; revision=477

diff --git a/src/ship_safari b/src/ship_safari
--- a/src/ship_safari
+++ b/src/ship_safari
@@ -3,8 +3,13 @@ cd $(dirname $0)
 dir=$(basename $(pwd))
 cd ..
 
-v=$(echo $(grep '<string>10[0-9]\.' $dir/Info.plist))
-echo -n "You expect to ship version $v, right? (y/n) "
+v=$(grep -A 1 'CFBundleVersion' $dir/Info.plist | tail -1 | cut -d '>' -f 2 | cut -d '<' -f 1)
+vd=$(grep -A 1 'CFBundleShortVersionString' $dir/Info.plist | tail -1 | cut -d '>' -f 2 | cut -d '<' -f 1)
+[ "10$vd" = "$v" ] || {
+  echo "Bundle version in Info.plist isn't 100 + display version."
+  exit 1
+}
+echo -n "You expect to ship version $v (displayed as $vd), right? (y/n) "
 read answer
 [ "$answer" = y ] || exit 1
 
@@ -15,3 +20,33 @@ tar czvf AdBlockForSafari.tgz $sdir
 clear
 echo Built AdBlockForSafari.tgz.
 echo Now load $sdir into Safari and build safaribuild.safariextz.
+echo Press enter when done.
+read
+
+[ -f safaribuild_tempdir.safariextz ] || {
+  echo "safaribuild_tempdir.safariextz needs to be in the same folder as AdBlockForSafari.tgz."
+  exit 1
+}
+
+echo -n "Type your username: "
+read user
+ssh="ssh $user@safariadblock.com"
+
+rdir="webapps/mg_safariadblock_com"
+$ssh "[ -d $rdir/versions/$vd ]" && {
+  echo "Sorry, version $vd already exists on the server."
+  exit 1
+}
+
+$ssh "mkdir $rdir/versions/$vd"
+
+scp safaribuild_tempdir.safariextz $user@safariadblock.com:$rdir/versions/$vd/AdBlockForSafari.safariextz || {
+  echo "Failed to scp"
+  exit 1
+}
+scp AdBlockForSafari.tgz $user@safariadblock.com:$rdir/versions/$vd/ || {
+  echo "Failed to scp"
+  exit 1
+}
+
+$ssh "$rdir/point_to_version $vd"
